### ISSUE TITLE
In use?

### ISSUE THREAD

**Issue by ChristopherA** [aergoio/secp256k1-vrf#1]
Is this VRF in use anywhere? 

Any other code implementions of VRFs in secp?

Any future plans? 

See also: https://github.com/ElementsProject/secp256k1-zkp/issues/190

**Comment by kroggen** [comment]
Yes, it is used in at least 3 projects. And maybe also on projects from other people.

**Comment by ChristopherA** [comment]
Have you looked into basing it on the -zkp branch from Blockstream? It may have export the functions you need. If not, if we ask nicely they might export them.

**Comment by kroggen** [comment]
I am happy with the current implementation. Our products do not have any requirement on ZKP

Feel comfortable to fork it and merge, if you wish
